services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  zipkin:
    image: openzipkin/zipkin-slim

  dapr-placement:
    image: "daprio/dapr:1.4.3"

  gateway:
    image: ${REGISTRY:-parusrx}/gateway:${TAG:-latest}

  gateway-dapr:
    image: "daprio/daprd:1.4.3"
    network_mode: "service:gateway"
    depends_on:
      - gateway

  directumrx:
    image: ${REGISTRY:-parusrx}/directumrx:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Dockerfile

  directumrx-dapr:
    image: "daprio/daprd:1.4.3"
    network_mode: "service:directumrx"
    depends_on:
      - directumrx
